# Default values for sgroups-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

type: DaemonSet # Deployment
replicaCount: 1
terminationGracePeriodSeconds: 30

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  agent:
    metrics: 9660
  collector:
    metrics: 9680

# Additional volumes on the output Deployment definition.
volumes: []
nodeSelector: {}
tolerations: []
affinity: {}

# Agent container configuration
agent:
  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    repository: prorobotech/sgroups-agent
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  extraEnv:
    NFT_DEF_POLICY_ACCEPT: "true"

  securityContext:
    allowPrivilegeEscalation: true
    privileged: true
    runAsNonRoot: false
    runAsUser: 0

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http

  # Additional volumeMounts on the output Deployment definition.
  volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

  config:
    hostinfo:
      name: host-example
      namespace: "incloud-sgroups"
    exit-on-success: false
    graceful-shutdown: 10s
    def-policy-accept: true
    logger:
      level: DEBUG
    fqdn-rules:
      strategy: dns
    extapi:
      svc:
        def-daial-duration: 10s
        sgroups:
          dial-duration: 3s
          address: sgroups:9006
          sync-status:
            interval: 3s #mandatory
          #check-sync-status: 5s
          use-json-codec: false
          # api-path-prefix: "/apis/sgroups.io/v1"
          authn:
            type: none
            # tls:
            #   key-file: "/opt/h-bf/sgroups/tls/tls.key"
            #   cert-file: "/opt/h-bf/sgroups/tls/tls.crt"
            #   server:
            #     verify: true
            #     ca-files:
            #       - "/opt/h-bf/sgroups/tls/ca.crt"
    netlink:
      watcher: #netlink watcher
        linger: 1s
    base-rules: |
      [
        {
          "nets": [
            "10.0.0.0/16",
            "10.0.1.0/24",
            "10.244.0.0/16",
            "29.64.0.0/16",
            "8.8.8.8/32"
            ]
        }
      ]
    dns:
      nameservers: ["8.8.8.8"]
      proto: udp
      port: 53
      dial-duration: 3s
      read-duration: 5s
      write-duration: 5s
      retries: 5
      retry-timeout: 3s
    telemetry:
      useragent: "string"
      endpoint: 0.0.0.0:9660
      metrics:
        enable: true
      healthcheck:
        enable: true
      profile:
        enable: true

hosthooks:
  enabled: true
  image:
    repository: alpine/kubectl
    pullPolicy: IfNotPresent
    tag: 1.33.4
  extraEnv: {}
    # EXAMPLE_ENV: "example-value"
  lifecycle:
    postStart: |
      kubectl apply -f - <<EOF
      ---
      apiVersion: netguard.sgroups.io/v1beta1
      kind: Host
      metadata:
        name: ${NFT_HOSTNAME}
        namespace: ${NFT_NAMESPACE}
      spec:
        uuid: ${NFT_UID}
      EOF
    preStop: |
      kubectl -n ${NFT_NAMESPACE} delete hosts.netguard.sgroups.io ${NFT_HOSTNAME}
  resources: {}

# Collector container configuration
collector:
  enabled: true
  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    repository: heaphero/prd.trace-collector
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: feature-cloud-87-tls-c4931993

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  livenessProbe:
    httpGet:
      path: /
      port: metrics
  readinessProbe:
    httpGet:
      path: /
      port: metrics

  # Additional volumeMounts on the output Deployment definition.
  volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

  config:
    logger:
        level: DEBUG
    trace-provider:
        use-aggregation: false
        queue-size: 2000000
        collector:
          type: netlink
          ebpf:
            rcv-buffer-size: 16777216
            sample-rate: 0
            events-rate: 5
          netlink:
            rcv-buffer-size: 16777216
    trace-exporter:
        target: server
        server:
          dial-duration: 3s
          address: prd-server:9650
          compression: none
          authn:
            type: none # tls
            # tls:
            #   key-file: "/opt/h-bf/sgroups/tls/tls.key"
            #   cert-file: "/opt/h-bf/sgroups/tls/tls.crt"
            #   server:
            #     verify: true
            #     ca-files:
            #       - "/opt/h-bf/sgroups/tls/ca.crt"
    tracer:
        flush-interval: 1s
        batch-size: 10000
    telemetry:
        endpoint: tcp://0.0.0.0:9680
        metrics:
          enable: true
        healthcheck:
          enable: true

debug:
  enabled: true
  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  image:
    repository: heaphero/prd.debug
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: main-2db719de

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http

  # Additional volumeMounts on the output Deployment definition.
  volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true
