---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "sgroups-k8s-api.fullname" . }}-config"
  labels:
    {{- include "sgroups-k8s-api.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
