---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ include "sgroups-k8s-api.fullname" . }}:system:auth-delegator"
  labels:
    {{- include "sgroups-k8s-api.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: {{ include "sgroups-k8s-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
