---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sgroups
  namespace: incloud-argocd
spec:
  destination:
    namespace: incloud-sgroups
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: registry-1.docker.io/prorobotech
    targetRevision: 0.0.0-feature-to-nft-787fbd2
    chart: sgroups-chart
    helm:
      releaseName: sgroups
      valuesObject:
        nameOverride: sgroups
        fullnameOverride: sgroups
        externalDatabase:
          enabled: false
        postgresql:
          enabled: true
          primary:
            persistence:
              enabled: false
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 256Mi
          readReplicas:
            persistence:
              enabled: false
        databaseConnectionStringArgs: null
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sgroups-agent
  namespace: incloud-argocd
spec:
  destination:
    namespace: incloud-sgroups
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: registry-1.docker.io/prorobotech
    targetRevision: 0.0.0-feature-to-nft-787fbd2
    chart: sgroups-agent-chart
    helm:
      releaseName: sgroups-agent
      valuesObject:
        fullnameOverride: sgroups-agent
        nameOverride: sgroups-agent
        agent:
          config:
            base-rules: |
              [
                {
                  "nets": [
                    "0.0.0.0/0"
                  ]
                }
              ]
        collector:
          enabled: false
        debug:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sgroups-k8s-api
  namespace: incloud-argocd
spec:
  destination:
    namespace: incloud-sgroups
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: registry-1.docker.io/prorobotech
    targetRevision: 0.0.0-feature-to-nft-787fbd2
    chart: sgroups-k8s-api-chart
    helm:
      releaseName: sgroups-k8s-api
      valuesObject:
        nameOverride: sgroups-k8s-api
        fullnameOverride: sgroups-k8s-api
        config:
          grpc:
            address: "sgroups.incloud-sgroups.svc:9006"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
