---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sgroups
  namespace: incloud-argocd
spec:
  destination:
    namespace: incloud-sgroups
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: registry-1.docker.io/prorobotech
    targetRevision: 0.0.1-eb88d40
    chart: sgroups-chart
    helm:
      releaseName: sgroups
      valuesObject:
        externalDatabase:
          enabled: false
        postgresql:
          enabled: true
          primary:
            persistence:
              enabled: false
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 256Mi
          readReplicas:
            persistence:
              enabled: false

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sgroups-k8s-api
  namespace: incloud-argocd
spec:
  destination:
    namespace: incloud-sgroups
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: registry-1.docker.io/prorobotech
    targetRevision: 0.0.1-eb88d40
    chart: sgroups-k8s-api-chart
    helm:
      releaseName: sgroups-k8s-api
      valuesObject:
        config:
          grpc:
            address: "sgroups.incloud-sgroups.svc:9006"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
