{{- if .Values.hosthooks.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sgroups-agent.fullname" . }}
  namespace: {{ $.Release.Namespace }}
rules:
  - apiGroups:
      - sgroups.io
    resources:
      - hosts
      - tenants
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
{{- end }}
