
{{- $dbUrl      := "" }}
{{- $dbPort     := "" }}
{{- $dbName     := "" }}
{{- $dbUsername := "" }}
{{- $dbPassword := "" }}
{{- $extPG := .Values.externalDatabase -}}
{{- $pg := .Values.postgresql -}}

{{- if $extPG.enabled }}
{{- $dbUrl      = $extPG.url }}
{{- $dbPort     = $extPG.port }}
{{- $dbName     = $extPG.database }}
{{- $dbUsername = $extPG.username }}
{{- $dbPassword = $extPG.password }}
{{- else }}
{{- $dbUrl      = printf "%s-postgresql.%s.svc" $.Release.Name $.Release.Namespace }}
{{- $dbPort     = $pg.primary.service.ports.postgresql }}
{{- $dbName     = $pg.auth.database }}
{{- $dbUsername = $pg.auth.username }}
{{- $dbPassword = $pg.auth.password }}
{{ end }}

{{- $connArgs := .Values.databaseConnectionStringArgs | default dict }}
{{- $queryList := list }}

{{- range $key, $value := $connArgs }}
  {{- if $value }}
    {{- $queryList = append $queryList (printf "%s=%s" ($key | toString) ($value | toString)) }}
  {{- end }}
{{- end }}

{{- $queryString := "" }}
{{- if gt (len $queryList) 0 }}
  {{- $queryString = printf "?%s" (join "&" $queryList) }}
{{- end }}

{{- $connString       := printf "postgres://%s:%s@%s:%v/%s" $dbUsername $dbPassword $dbUrl $dbPort $dbName }}
{{- $connStringGoose  := printf "%s?sslmode=disable" $connString }}
{{- $connStringApp    := printf "%s%s" $connString $queryString }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sgroups.fullname" . }}-database
  labels:
    {{- include "sgroups.labels" . | nindent 4 }}
stringData:
  DATABASE_URL:             "{{ $dbUrl }}"
  DATABASE_PORT:            "{{ $dbPort }}"
  DATABASE_NAME:            "{{ $dbName }}"
  DATABASE_USERNAME:        "{{ $dbUsername }}"
  DATABASE_PASSWORD:        "{{ $dbPassword }}"
  SG_GOOSE_POSTGRES_URL:    "{{ $connStringGoose }}"
  SG_STORAGE_POSTGRES_URL:  "{{ $connStringApp }}"
