
{{- $dbUrl      := "" }}
{{- $dbPort     := "" }}
{{- $dbName     := "" }}
{{- $dbUsername := "" }}
{{- $dbPassword := "" }}
{{- $extPG := .Values.externalDatabase -}}
{{- $pg := .Values.postgresql -}}

{{- if $extPG.enabled }}
{{- $dbUrl      = $extPG.url | urlquery }}
{{- $dbPort     = $extPG.port }}
{{- $dbName     = $extPG.database | urlquery }}
{{- $dbUsername = $extPG.username | urlquery }}
{{- $dbPassword = $extPG.password | urlquery }}
{{- else }}
{{- $dbUrl      = printf "%s-postgresql.%s.svc" $.Release.Name $.Release.Namespace }}
{{- $dbPort     = $pg.primary.service.ports.postgresql }}
{{- $dbName     = $pg.auth.database | urlquery }}
{{- $dbUsername = $pg.auth.username | urlquery }}
{{- $dbPassword = $pg.auth.password | urlquery }}
{{ end }}

{{- $connectionString := "postgres://{{ $dbUsername }}:{{ $dbPassword }}@{{ $dbUrl }}:{{ $dbPort }}/{{ $dbName }}" }}

{{- $connArgs := .Values.databaseConnectionStringArgs | default dict }}
{{- $queryList := list }}

{{- range $key, $value := $connArgs }}
  {{- if $value }}
    {{- $queryList = append $queryList (printf "%s=%v" $key $value) }}
  {{- end }}
{{- end }}

{{- $queryString := "" }}
{{- if gt (len $queryList) 0 }}
  {{- $queryString = printf "?%s" (join "&" $queryList) }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sgroups.fullname" . }}-database
  labels:
    {{- include "sgroups.labels" . | nindent 4 }}
stringData:
  DATABASE_URL:             "{{ $dbUrl }}"
  DATABASE_PORT:            "{{ $dbPort }}"
  DATABASE_NAME:            "{{ $dbName }}"
  DATABASE_USERNAME:        "{{ $dbUsername }}"
  DATABASE_PASSWORD:        "{{ $dbPassword }}"
  SG_GOOSE_POSTGRES_URL:    "{{ $connectionString }}?sslmode=disable"
  SG_STORAGE_POSTGRES_URL:  "{{ $connectionString }}{{ $queryString }}"
