apiVersion: apps/v1
{{- if eq .Values.type "Deployment" }}
kind: Deployment
{{- else }}
kind: DaemonSet
{{- end }}
metadata:
  name: {{ include "to-nft.fullname" . }}
  labels:
    {{- include "to-nft.labels" . | nindent 4 }}
spec:
  {{- if and (not .Values.autoscaling.enabled) (eq .Values.type "Deployment") }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "to-nft.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "to-nft.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "to-nft.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: agent
          {{- with .Values.agent.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              /app/bin/to-nft --config /opt/h-bf/sgroups/client/config.yaml
          {{- with .Values.agent.lifecycle }}
          lifecycle:
            {{- if .postStart }}
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - {{ .postStart | quote }}
            {{- end }}
            {{- if .preStop }}
            preStop:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - {{ .preStop | quote }}
            {{- end }}
          {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NFT_HOSTINFO_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            {{- range $k, $v := .Values.agent.extraEnv }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.agent.metrics }}
              protocol: TCP
          {{- with .Values.agent.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.agent.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.agent.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: agent-config
              mountPath: /opt/h-bf/sgroups/client/
              readOnly: true
          {{- with .Values.agent.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.collector.enabled }}
        - name: debug
          {{- with .Values.collector.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.collector.image.repository }}:{{ .Values.collector.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.collector.image.pullPolicy }}
          command: []
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NFT_HOSTINFO_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            {{- range $k, $v := .Values.agent.extraEnv }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.agent.metrics }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: agent-config
              mountPath: /opt/h-bf/sgroups/client/
              readOnly: true
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if .Values.debug.enabled }}
        - name: debug
          {{- with .Values.debug.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.debug.image.repository }}:{{ .Values.debug.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.debug.image.pullPolicy }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              /app/bin/to-nft --config /opt/h-bf/sgroups/client/config.yaml
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NFT_HOSTINFO_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            {{- range $k, $v := .Values.agent.extraEnv }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.agent.metrics }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: agent-config
              mountPath: /opt/h-bf/sgroups/client/
              readOnly: true
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
      volumes:
        - name: agent-config
          configMap:
            name: {{ include "to-nft.fullname" . }}-agent-config
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
