---
# Collector configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "to-nft.fullname" . }}-collector-config
  labels:
    {{- include "to-nft.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
data:
  config.yaml: |
    {{ .Values.collector.config | toYaml | nindent 4 }}
