apiVersion: v1
kind: Service
metadata:
  name: {{ include "to-nft.fullname" . }}
  labels:
    {{- include "to-nft.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.agent.metrics }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "to-nft.selectorLabels" . | nindent 4 }}
