apiVersion: v1
kind: Service
metadata:
  name: {{ include "to-nft.fullname" . }}
  labels:
    {{- include "to-nft.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.agent.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- if .Values.collector.enabled }}
    - port: {{ .Values.service.collector.metrics | default 9680 }}
      targetPort: collector
      protocol: TCP
      name: collector
    {{- end }}
  selector:
    {{- include "to-nft.selectorLabels" . | nindent 4 }}
